[workspace]
members = [
	"consensus",
	"network",
	"runtime",
	"test/runtime",
	"test/client",
	"test/parachain/runtime",
	"test/parachain/",
	"test/parachain/runtime/wrapped-dot",
]

[profile.release]
panic = 'unwind'
