[package]
name = "cumulus-network"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Cumulus-specific networking protocol"
edition = "2018"

[dependencies]
# substrate deps
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "cecton-ensure-replay-parent-eq-relay-head" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "cecton-ensure-replay-parent-eq-relay-head" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "cecton-ensure-replay-parent-eq-relay-head" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "cecton-ensure-replay-parent-eq-relay-head" }

# polkadot deps
polkadot-collator = { git = "https://github.com/paritytech/polkadot", branch = "cecton-ensure-replay-parent-eq-relay-head" }
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "cecton-ensure-replay-parent-eq-relay-head" }
polkadot-statement-table = { git = "https://github.com/paritytech/polkadot", branch = "cecton-ensure-replay-parent-eq-relay-head" }
polkadot-validation = { git = "https://github.com/paritytech/polkadot", branch = "cecton-ensure-replay-parent-eq-relay-head" }
polkadot-network = { git = "https://github.com/paritytech/polkadot", branch = "cecton-ensure-replay-parent-eq-relay-head" }

# other deps
codec = { package = "parity-scale-codec", version = "1.3.0", features = [ "derive" ] }
futures = { version = "0.3.1", features = ["compat"] }
log = "0.4.8"
parking_lot = "0.10.2"

[dev-dependencies]
polkadot-test-runtime-client = { git = "https://github.com/paritytech/polkadot", branch = "cecton-ensure-replay-parent-eq-relay-head" }
cumulus-test-runtime = { path = "../test/runtime" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "cecton-ensure-replay-parent-eq-relay-head" }
polkadot-test-runtime = { git = "https://github.com/paritytech/polkadot", branch = "cecton-ensure-replay-parent-eq-relay-head" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "cecton-ensure-replay-parent-eq-relay-head" }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "cecton-ensure-replay-parent-eq-relay-head" }
sp-state-machine = { git = "https://github.com/paritytech/substrate", branch = "cecton-ensure-replay-parent-eq-relay-head" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "cecton-ensure-replay-parent-eq-relay-head" }
